// Writes docs/CODEMAP.md: a map of the big files (line numbers of every class, method, top-level function, and each scenario's `case`), so a file of thousands of lines can be
// entered at the right place instead of read from the top.   node tools/codemap.mjs [--check]   (--check exits 1 when the committed map is stale)
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const pack = path.join(root, 'behavior_pack/scripts');
const MIN = 400;
const files = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => e.isDirectory() ? files(path.join(d, e.name)) : e.name.endsWith('.js') ? [path.join(d, e.name)] : []);

export function mapOf(src, rel) {
  const lines = src.split('\n'), out = [];
  const push = (n, text) => out.push(`${n}`.padStart(5) + '  ' + text);
  lines.forEach((l, i) => {
    let m;
    if ((m = /^export\s+(?:async\s+)?class\s+(\w+)/.exec(l)) || (m = /^class\s+(\w+)/.exec(l))) push(i + 1, `class ${m[1]}`);
    else if ((m = /^(?:export\s+)?(?:async\s+)?function\*?\s+(\w+)/.exec(l))) push(i + 1, `${l.startsWith('export') ? 'export ' : ''}${/async/.test(l.split('(')[0]) ? 'async ' : ''}function ${m[1]}`);
    else if ((m = /^export\s+const\s+(\w+)\s*=\s*(?:async\s*)?\(/.exec(l))) push(i + 1, `export const ${m[1]} = (…)`);
    else if ((m = /^  (?:async\s+)?(?:static\s+)?(?:get\s+|set\s+)?([A-Za-z_$][\w$]*)\s*\([^)]*\)\s*\{\s*(?:\/\/.*)?$/.exec(l)) && !/^(if|for|while|switch|catch|return)$/.test(m[1])) push(i + 1, `  .${m[1]}()`);
    else if (rel.endsWith('game/scenarios.js') && (m = /^      case '([a-z0-9]+)'(?:: case '([a-z0-9]+)')*/.exec(l))) push(i + 1, `  test ${[...l.matchAll(/case '([a-z0-9]+)'/g)].map((x) => x[1]).join(', ')}`);
  });
  return out;
}

export function build() {
  const parts = ['# Code map', '', `Generated by \`node tools/codemap.mjs\` (line numbers drift as files change: rerun it; --check says whether it is stale). Files over ${MIN} lines: line number, then what starts there. Go to the line instead of reading from the top.`, ''];
  for (const f of files(pack).sort()) {
    const src = fs.readFileSync(f, 'utf8');
    const n = src.split('\n').length;
    if (n < MIN) continue;
    const rel = path.relative(root, f).replaceAll('\\', '/');
    parts.push(`## ${rel} (${n} lines)`, '', '```', ...mapOf(src, rel), '```', '');
  }
  return parts.join('\n');
}

if (process.argv[1].endsWith('codemap.mjs')) {
  const out = path.join(root, 'docs/CODEMAP.md'), text = build();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    console.log(cur === text ? 'codemap current' : 'docs/CODEMAP.md is stale: run node tools/codemap.mjs');
    process.exit(cur === text ? 0 : 1);
  }
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, text);
  console.log(`wrote docs/CODEMAP.md (${text.split('\n').length} lines)`);
}
