// Generates behavior_pack/scripts/core/vanilla.js from Mojang's bedrock-samples (the vanilla behavior pack: every mob's health, attack, speed, size, ...). The numbers the bot
// would otherwise guess come from here, and tests/vanilla.test.js holds our hand-tuned tables (core/threat.js MOBS) to them.
//   git clone --depth 1 https://github.com/Mojang/bedrock-samples ; node tools/gen_vanilla.mjs <path to bedrock-samples>
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { readJ } from './lenient_json.mjs';

const root = process.argv[2];
if (!root) { console.error('usage: node tools/gen_vanilla.mjs <bedrock-samples dir>'); process.exit(1); }
const dir = `${root}/behavior_pack/entities`;
let commit = 'unknown';
try { commit = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim(); } catch { /* not a clone */ }

/** A component from the base set, else from the first component group that has it (groups with "baby" in the name are skipped: we want the grown mob). */
function find(e, key) {
  if (e.components?.[key] !== undefined) return e.components[key];
  for (const [g, v] of Object.entries(e.component_groups ?? {})) if (!/baby/.test(g) && v?.[key] !== undefined) return v[key];
  return undefined;
}
const num = (v) => (typeof v === 'number' ? v : typeof v?.value === 'number' ? v.value : typeof v?.max === 'number' ? v.max : undefined);
const round = (v) => (typeof v === 'number' ? Math.round(v * 1000) / 1000 : v);
const out = {};
for (const f of readdirSync(dir).filter((x) => x.endsWith('.json')).sort()) {
  let e;
  try { e = readJ(`${dir}/${f}`)['minecraft:entity']; } catch (err) { console.error('skip', f, String(err).slice(0, 80)); continue; }
  if (!e) continue;
  const id = e.description.identifier.replace('minecraft:', ''), m = {};
  const hp = num(find(e, 'minecraft:health')); if (hp !== undefined) m.hp = hp;
  const atk = find(e, 'minecraft:attack');
  if (atk) { const d = atk.damage; if (typeof d === 'number') m.atk = d; else if (Array.isArray(d)) m.atk = d[0]; else if (d?.range_min !== undefined) { m.atkMin = d.range_min; m.atkMax = d.range_max; } if (atk.effect_name) m.atkEffect = atk.effect_name; }
  const mv = num(find(e, 'minecraft:movement')); if (mv !== undefined) m.speed = round(mv);
  // how fast it closes on a target: the movement attribute times its chase goal's speed_multiplier (a creeper 0.2 x 1.25, a zombie 0.23 x 1)
  const chase = find(e, 'minecraft:behavior.melee_attack') ?? find(e, 'minecraft:behavior.melee_box_attack');
  if (mv !== undefined && chase) m.chase = round(mv * (chase.speed_multiplier ?? 1));
  const kb = num(find(e, 'minecraft:knockback_resistance')); if (kb !== undefined) m.kbRes = kb;
  const fr = num(find(e, 'minecraft:follow_range')); if (fr !== undefined) m.follow = fr;
  const cb = find(e, 'minecraft:collision_box'); if (cb?.width) m.box = [round(cb.width), round(cb.height)];
  const fam = find(e, 'minecraft:type_family')?.family; if (fam) m.family = fam.filter((x) => x !== id);
  if (find(e, 'minecraft:burns_in_daylight') !== undefined) m.burnsInDaylight = true;
  if (find(e, 'minecraft:explode')) { const x = find(e, 'minecraft:explode'); m.explode = { radius: x.power ?? x.radius, fuse: x.fuse_length }; }
  const ranged = find(e, 'minecraft:behavior.ranged_attack') ?? find(e, 'minecraft:behavior.ranged_bow_attack') ?? find(e, 'minecraft:behavior.random_fly_shoot') ?? find(e, 'minecraft:behavior.shoot');
  const rg = (v) => (v && typeof v === 'object' && !Array.isArray(v) ? [v.min, v.max] : v);
  if (ranged) m.ranged = { interval: rg(ranged.attack_interval) ?? [ranged.attack_interval_min, ranged.attack_interval_max].filter((v) => v !== undefined), radius: rg(ranged.attack_radius ?? ranged.attack_range) };
  const sw = find(e, 'minecraft:behavior.swell'); if (sw) m.swell = { start: sw.start_distance, stop: sw.stop_distance };
  if (find(e, 'minecraft:is_baby') === undefined && find(e, 'minecraft:fire_immune') !== undefined) m.fireImmune = true;
  if (find(e, 'minecraft:leashable') !== undefined) m.leashable = true;
  if (find(e, 'minecraft:rideable') !== undefined) m.rideable = true;
  out[id] = m;
}
const body = `// GENERATED by tools/gen_vanilla.mjs from Mojang/bedrock-samples @ ${commit} (${Object.keys(out).length} entities). Do not edit: rerun the generator. The vanilla numbers the bot's own
// tables are held to (tests/vanilla.test.js). hp, atk (flat damage) or atkMin/atkMax, speed (movement attribute), kbRes, follow (blocks), box [width, height], family, ...
export const VANILLA_SOURCE = 'bedrock-samples@${commit}';
export const VANILLA = Object.freeze(${JSON.stringify(out, null, 0).replace(/},"/g, '},\n  "')});
`;
writeFileSync(new URL('../behavior_pack/scripts/core/vanilla.js', import.meta.url), body);
console.log(`wrote ${Object.keys(out).length} entities, bedrock-samples@${commit}`);
