// Writes behavior_pack/scripts/core/hardness_data.js from PrismarineJS minecraft-data (Bedrock): block name -> hardness for every diggable block.
//   MCDATA_DIR=<folder with node_modules/minecraft-data> node tools/gen_hardness.mjs [bedrock_1.21.60]
import { createRequire } from 'node:module';
import fs from 'node:fs';
const req = createRequire((process.env.MCDATA_DIR ?? process.cwd()) + '/');
const d = req('minecraft-data')(process.argv[2] ?? 'bedrock_1.21.60');
const out = {};
for (const b of d.blocksArray) if (b.diggable && b.hardness != null && b.hardness >= 0) out[b.name] = b.hardness;
const body = `// Generated by tools/gen_hardness.mjs from PrismarineJS minecraft-data (${process.argv[2] ?? 'bedrock_1.21.60'}); do not edit. Block name -> hardness, diggable blocks only.\n`
  + `export const HARDNESS_DATA = ${JSON.stringify(out)};\n`;
fs.writeFileSync(new URL('../behavior_pack/scripts/core/hardness_data.js', import.meta.url), body);
console.log(`${Object.keys(out).length} blocks`);
